#!/bin/env bash

set -e


# Format python code
if command -v black &> /dev/null; then
  black --line-length 100 *.py
else
  echo "[Warning]: black not found, skipping Dockerfile formatting"
fi

# Format dockerfile
if command -v nix-shell &> /dev/null; then
  nix-shell -p dockerfmt --run "dockerfmt Dockerfile" > tmp
  mv tmp Dockerfile
else
  echo "[Warning]: dockerfmt not found, skipping Dockerfile formatting"
fi


# Stage formatted files
STAGED_PYTHON_FILES=$(git diff --name-only --cached --relative | grep '\.py$')
if [ -n "$STAGED_PYTHON_FILES" ]; then
  echo "$STAGED_PYTHON_FILES" | xargs git add
fi
